title: Your awesome title
author: author
email: your@email.com
description: El Psy Congroo

# socail links
github_username: jekyll
rss: rss

excerpts:
  enable: true
  length: 300

# remote_theme: kemingy/jekyll-theme-ink

permalink: /blog/:title

favicon:
  enable: false
  name: favicon.ico

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

markdown: kramdown
kramdown:
  input: GFM

mathjax:
  enable: true
  cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-MML-AM_CHTML

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!-- more -->

jekyll-archives:
  enabled: [categories, year, month, tags]
  layouts:
    category: 'category'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
    category: '/category/:name/'

